name: Mastodon (main)
on:
  push:
    branches:
    - main
jobs:
  toot:
    name: Toot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Toot
        uses: joschi/toot-together@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MASTODON_URL: https://botsin.space/
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
