name: Mastodon (PR)
on:
  pull_request:
    branches:
    - main
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: joschi/toot-together@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
