name: "@asdf_vm@masto.to"
on:
  push:
    branches:
    - main
    paths:
    - toots/**
  workflow_dispatch:
jobs:
  toot:
    name: Toot (@asdf_vm@mas.to)
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Add new toots') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Toot
        uses: joschi/toot-together@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          MASTODON_URL: https://mas.to
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTO_ACCESS_TOKEN }}
