name: Mastodon (main)
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  toot:
    name: Toot
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Add new toots') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toot
        uses: joschi/toot-together@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          MASTODON_URL: https://botsin.space/
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
