name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: mstksg/get-package@v1
      with:
        apt-get: shellcheck
    - name: Run ShellCheck
      run: |
        shellcheck -V
        shellcheck -x bin/*.bash
