name: Test
on:
  push:
    paths:
    - .github/**
    - bin/**
  pull_request:
    paths:
    - .github/**
    - bin/**

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v5
    - name: Install ShellCheck
      run: sudo apt install shellcheck
    - name: Run ShellCheck
      run: |
        shellcheck -V
        shellcheck -x bin/*.bash
