name: Twitter (PR)
on:
  pull_request:
    branches:
    - main
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: twitter-together/action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
