name: Twitter (main)
on:
  push:
    branches:
    - main
    paths:
    - tweets/**
  workflow_dispatch:
jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Add new tweets') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tweet
        uses: twitter-together/action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
