name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Install dependencies
      run: sudo apt -y install parallel
    - name: Set up asdf-vm
      uses: asdf-vm/actions/setup@v3.0.0
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.asdf/repository
        key: ${{ runner.os }}-plugins
    - name: Run update script
      env:
        GITHUB_API_TOKEN: ${{ secrets.PULL_TOKEN }}
        OAUTH_TOKEN: ${{ secrets.PULL_TOKEN }}
      run: ./bin/update.bash
    - name: Commit metadata changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Update plugin and versions metadata"
        add: "data/"
        pull: '--rebase --autostash'
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
    - name: Commit new tweets
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Add new tweets 🐦"
        add: "tweets/"
        pull: '--rebase --autostash'
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
    - name: Commit new toots
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Add new toots 🐘"
        add: "toots/"
        pull: '--rebase --autostash'
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
