name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
concurrency:
  group: "update"
  cancel-in-progress: false
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Install dependencies
      run: sudo apt -y install parallel
    - name: Set up asdf-vm
      uses: asdf-vm/actions/setup@v4.0.0
    - name: Run update script
      env:
        GITHUB_API_TOKEN: ${{ secrets.PULL_TOKEN }}
        OAUTH_TOKEN: ${{ secrets.PULL_TOKEN }}
      run: ./bin/update.bash
    - name: Commit metadata changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Update plugin and versions metadata"
        add: "data/"
        pull: '--rebase --autostash'
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
    - name: Copy RSS feed for upload
      run: |
          mkdir -p _site
          cp data/feed.rss _site/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
    - name: Commit new tweets
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Add new tweets 🐦"
        add: "tweets/"
        pull: '--rebase --autostash'
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
    - name: Commit new toots
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Add new toots 🐘"
        add: "toots/"
        pull: '--rebase --autostash'
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
    - name: Commit new RSS items
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Add new RSS items"
        add: "rss/"
        pull: '--rebase --autostash'
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
  deploy:
    needs: update
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
