name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt -y install parallel
    - name: Set up asdf-vm
      uses: asdf-vm/actions/setup@v1.1.0
    - name: Checkout asdf-plugins repo
      uses: actions/checkout@v3
      with:
        repository: asdf-vm/asdf-plugins
        path: asdf-plugins
        token: ${{ secrets.PULL_TOKEN }}
    - name: Run update script
      run: ./bin/update.bash
    - name: Commit metadata changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Update plugin and versions metadata"
        add: "data/"
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
    - name: Commit new tweets
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Add new tweets 🐦"
        add: "tweets/"
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
    - name: Commit new toots
      uses: EndBug/add-and-commit@v9
      with:
        message: "🤖 Add new toots 🐘"
        add: "toots/"
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
